Setup Viper with flags
ConsenSys/fc-retrieval-client pull request #20
Opened 2021-02-05 10:17 UTC by ssaidali

2021-02-07 23:17 UTC, drinkcoffee requested changes

2021-02-07 23:17 UTC, drinkcoffee commented on .circleci/config.yml
> +      # - run: make detectmisconfig
Having detectmisconfig is important. It will ensure the client is using the correct version of the gateway (either latest on branch or latest on main).

2021-02-07 23:17 UTC, drinkcoffee commented on Dockerfile
>  # Do a full compile of app and dependancies, forcing static linking.
We should be removing the Docker files from the client repo. The client is a library.

2021-02-07 23:17 UTC, drinkcoffee commented on cmd/client/integration-tests.go
>  import (
The integration test code should be removed. There is integration test code in the itest repo

2021-02-08 09:38 UTC, ssaidali commented
This PR is not relevant anymore because the client has no need for Viper

2021-02-08 09:38 UTC, closed without merging

2021-02-08 09:38 UTC, ssaidali commented
This PR is not relevant anymore because the client has no need for Viper